print("hello".find('e'))
print("hello".find('r'))
print("banana".replace("na","la"))
print("I,am,ok,now".split(','))
print("Get.Lost.From.Here".split('.'))
print("**".join(['hi','hello','bye']))
print("hi hello weclome".capitalize())
print("hi hello weclome".center(31,'*'))
print(len('********hi hello weclome*******'))
print('********hi hello weclome*******'.count('*'))
print("python".encode(encoding='utf-8',errors='strict'))
print('pythön'.encode(encoding='utf-8',errors='strict'))
print("hi hello weclome".endswith('come'))
print("hi hello weclcome".endswith('come'))
print("hi hello weclcome".index('e'))
#print("hi hello weclcome".index('r'))
print("123456789hello".isalnum())
print("hello".isalpha())
print("2021".isdecimal())
print("2021".isdigit())
print("try".isidentifier())
print("bye".islower())
print("HELLO".isupper())
print("   ".isspace())
print("Hello World".istitle())
print("hi HELLO bye".swapcase())
print("hi hello bye".title())
a="         hi hello welcome                "
print(a.strip())